export const UPDATE_POSTS="UPDATE_POSTS";
export const LOGIN_START="LOGIN_START";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILED="LOGIN_FAILED";
export const SIGNUP_START="SIGNUP_START";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGNUP_FAILED="SIGNUP_FAILED";
export const AUTHENTICATE_USER="AUTHENTICATE_USER";
export const LOG_OUT="LOG_OUT";
export const CLEAR_AUTH_STATE="CLEAR_AUTH_STATE";
export const EDIT_USER_SUCCESSFUL="EDIT_USER_SUCCESSFUL";
export const EDIT_USER_FAILED="EDIT_USER_FAILED";
export const USER_PROFILE_SUCCESSFUL="USER_PROFILE_SUCCESSFUL";
export const USER_PROFILE_FAILED="USER_PROFILE_FAILED";
export const FETCH_USER_PROFILE="FETCH_USER_PROFILE";
export const CLEAR_PROFILE_STATE="CLEAR_PROFILE_STATE";

export const FETCH_FRIENDS_SUCCCESS='FETCH_FRIENDS_SUCCCESS';
export const FETCH_FRIENDS_START='FETCH_FRIENDS_START';
export const FETCH_FRIENDS_FAILURE='FETCH_FRIENDS_FAILURE';

/* ADD FRIEND */
export const ADD_FRIEND='ADD_FRIEND';

/* REMOVE FRIEND */
export const REMOVE_FRIEND='REMOVE_FRIEND'

